version: '3.3'

networks:
  traefik:
    external: true

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.role == manager
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
    networks:
      - traefik
  web:
    image: 127.0.0.1:5000/trivagodemo
    deploy:
      replicas: 2 
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.port=8000"
      -  "traefik.enable=true"
    networks:
      - traefik
  mysql:
    image: 127.0.0.1:5000/trivagomysql
    ports:
    - target: 3306
      protocol: tcp
      published: 32000
      mode: ingress
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    labels: 
      - "traefik.enable=false"
    networks:
      - traefik