---

# tasks file for ansible-dockerized-trivago

- name: "Launch Load balancer container"
  docker:
    name: load-balancer
    image:  traefik
    command: "--api --docker"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
- name: "Launch database container"
  docker: 
    name: mysql
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    labels:
      - "traefik.enable=false"

- name: "Launch web app"
  docker:
    name: web
    image: 127.0.0.1:8000/trivagodemo
    build: . 
    links:
      - mysql:mysql:5.7
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.port=8000"